### ISSUE TITLE
Disparar eventos/data para o Facebook Pixel

### ISSUE THREAD

**Issue by leomp12** [ecomclub/widget-fb-pixel#1]
A integração aqui é bem próxima do que é feito para o Google Analytics ([e-commerce avançado via GTM](https://developers.google.com/tag-manager/enhanced-ecommerce?hl=pt-br)), então o source code do [widget-tag-manager](https://github.com/ecomclub/widget-tag-manager) pode servir como boa referência.

A intenção é enviar todos os dados possíveis, eventos como visualização de SKUs, adição ao carrinho, remoção do carrinho, steps do checkout (não sei exatamente quais eventos o pixel do FB suporta).

Acredito que o widget deverá receber como option (configurado no CMS) apenas o ID do pixel copiado do próprio Facebook.

:wave:

**Comment by leomp12** [comment]
@igorsfreitas pode me dar uma moral aqui?

**Comment by lojatiasonia** [comment]
https://www.simoahava.com/analytics/create-facebook-pixel-custom-tag-template/

**Comment by igorsfreitas** [comment]
https://www.simoahava.com/analytics/create-facebook-pixel-custom-tag-template/

**Comment by leomp12** [comment]
@lojatiasonia só pra registrar, este artigo seria pra você integrar manualmente via GTM, este widget vai integrar direto com o pixel seguindo a documentação deles

**Comment by igorsfreitas** [comment]
Tranquilo ! coloquei ai so p não perder o link

**Comment by igorsfreitas** [comment]
Boa noite @leomp12  ! Os eventos que fiz, foram baseado nas documentações:
https://developers.facebook.com/docs/facebook-pixel/advanced
https://developers.facebook.com/docs/facebook-pixel/reference/

Tinha esquecido de alterar os objetos e os tipos de evento, mas agora estão ok ! Preciso ver com vc como fazemos para testar.

Att,
